# Generated by Django 4.2 on 2023-04-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
                ('habilitacao', models.BooleanField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga_horaria_semanal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('horas_necessarias', models.IntegerField()),
                ('prazo_estimado', models.DateField()),
                ('horas_realizadas', models.IntegerField()),
                ('ultimo_calculo_horas', models.DateField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.departamento')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto_Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria_semanal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.funcionario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.projeto')),
            ],
            options={
                'unique_together': {('projeto', 'funcionario')},
            },
        ),
    ]
