# Generated by Django 4.2 on 2023-04-12 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ('nome',), 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ('nome',), 'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ('prazo_estimado',), 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Função Supervisor'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='projetos',
            field=models.ManyToManyField(related_name='funcionarios_projetos', through='management.Projeto_Funcionario', to='management.projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='carga_horaria_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projeto',
            name='funcionarios',
            field=models.ManyToManyField(related_name='funcionarios_projetos', through='management.Projeto_Funcionario', to='management.funcionario'),
        ),
        migrations.AddField(
            model_name='projeto_funcionario',
            name='funcao',
            field=models.CharField(choices=[('F', 'Funcionário'), ('S', 'Supervisor')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='carga_horaria_semanal',
            field=models.PositiveSmallIntegerField(verbose_name='Carga horária semanal'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='habilitacao',
            field=models.BooleanField(verbose_name='Possui habilitação'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(max_length=9, unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos', to='management.departamento'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='horas_necessarias',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='horas_realizadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_supervisionados', to='management.funcionario'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ultimo_calculo_horas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto_funcionario',
            name='carga_horaria_semanal',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Carga horária semanal'),
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
        migrations.AlterModelTable(
            name='projeto',
            table='projeto',
        ),
        migrations.AlterModelTable(
            name='projeto_funcionario',
            table='projeto_funcionario',
        ),
    ]
